version: '2'

services:

    myapp:
        image: rentrust-webapp:latest
        environment:
            - NODE_ENV=development
        ports:
          - 8080:3000
        working_dir: /webapp
        entrypoint: node app.js
        links:
          - mongodb
          - redis

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet

    redis:
        container_name: redis
        image: redis
        ports:
          - "6379:6379"
        entrypoint: redis-server --appendonly yes
        restart: always

